sudo: required

services:
 - docker

language: bash

env:
  matrix:
  - DOCKER_ARCH=amd64
  # - DOCKER_ARCH=arm64 problems with python and qemu
  - DOCKER_ARCH=arm

script:
- ./build/cicd_build.sh

jobs:
  include:

  - stage: Manifest
    script:
    - ./build/cicd_manifest.sh
    env:
